# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ofo_demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod ‘SWRevealViewController’
  pod ‘AMap3DMap’
  pod ‘AMapLocation’
  pod ‘AMapSearch’
  pod ‘AMapNavi’
  pod ‘FTIndicator’
  pod ‘swiftScan’
  pod ‘APNumberPad’
  pod ‘SwiftyTimer’
  pod ‘SwiftySound’
  pod ‘AVOSCloud’
  pod ‘MIBlurPopup’

end
